steps:
  - name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask_app:latest', '-t', 'gcr.io/$PROJECT_ID/flask_app:$COMMIT_SHA', '-T', 'gcr.io/$PROJECT_ID/flask_app:$BUILD_ID', '.'] 
  id: 'build-img-ffllaasskk_aappppp'
  waitFor: ['-']

  images:
    - 'gcr.io/$PROJECT_ID/flask_app:latest'
    - 'gcr.io/$PROJECT_ID/flask_app:$COMMIT_SHA'
    - 'gcr.io/$PROJECT_ID/flask_app:$BUILD_ID'

  artifacts:
    objects:
      location: 'gs://devops-$PROJECT_ID/$BUILD_ID'
      pths: ['artefacts.tar.gz']
