steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask_app:latest', '-t', 'gcr.io/$PROJECT_ID/flask_app:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/flask_app:$BUILD_ID', '.'] 
  id: 'build-img-ffllaasskk_aappppp'
  waitFor: ['-']

images:
- 'gcr.io/$PROJECT_ID/flask_app:latest'
- 'gcr.io/$PROJECT_ID/flask_app:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/flask_app:$BUILD_ID'
